In [ ]:
pip install pyarrow

In [8]:
import pyarrow

In [10]:
import pandas as pd

df = pd.read_parquet("./fhvhv_tripdata_2020-03.parquet")
df.head(5)

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag
0,HV0005,B02510,None,2020-03-01 00:00:12,NaT,2020-03-01 00:03:40,2020-03-01 00:23:39,81,159,8.655,...,1.90,0.00,NaN,0.0,19.65,N,N,N,N,N
1,HV0005,B02510,None,2020-03-01 00:22:03,NaT,2020-03-01 00:28:05,2020-03-01 00:38:57,168,119,3.523,...,0.85,0.00,NaN,0.0,9.37,N,N,N,N,N
2,HV0003,B02764,B02764,2020-02-29 23:57:45,2020-03-01 00:01:04,2020-03-01 00:03:07,2020-03-01 00:15:04,137,209,4.070,...,1.38,2.75,NaN,0.0,16.24,N,Y,,N,N
3,HV0003,B02764,B02764,2020-03-01 00:04:06,2020-03-01 00:15:48,2020-03-01 00:18:42,2020-03-01 00:38:42,209,80,4.730,...,1.23,0.75,NaN,0.0,21.76,Y,N,,N,N
4,HV0003,B02764,B02764,2020-03-01 00:42:46,2020-03-01 00:43:18,2020-03-01 00:44:24,2020-03-01 00:58:44,256,226,4.030,...,1.79,0.00,NaN,0.0,19.64,N,N,,N,N

In [13]:
df.describe()

,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,bcf,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay
count,1.339293e+07,1.339293e+07,1.339293e+07,1.339293e+07,1.339293e+07,1.339293e+07,1.339293e+07,1.339293e+07,1.339293e+07,24.0,1.339293e+07,1.339293e+07
mean,1.366155e+02,1.392192e+02,4.604680e+00,1.013237e+03,1.635973e+01,7.971854e-01,4.236022e-01,1.367589e+00,8.436457e-01,0.0,5.263801e-01,1.368324e+01
std,7.576037e+01,7.788180e+01,5.290254e+00,6.975439e+02,1.532755e+01,3.282952e+00,4.464393e-01,1.250174e+00,1.227085e+00,0.0,2.067542e+00,1.244444e+01
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,-1.282300e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,-2.393300e+02
25%,7.200000e+01,7.200000e+01,1.570000e+00,5.360000e+02,7.490000e+00,0.000000e+00,1.800000e-01,6.400000e-01,0.000000e+00,0.0,0.000000e+00,6.120000e+00
50%,1.380000e+02,1.380000e+02,2.862000e+00,8.370000e+02,1.179000e+01,0.000000e+00,2.900000e-01,9.900000e-01,0.000000e+00,0.0,0.000000e+00,1.039000e+01
75%,2.090000e+02,2.130000e+02,5.630000e+00,1.293000e+03,1.980000e+01,0.000000e+00,5.000000e-01,1.690000e+00,2.750000e+00,0.0,0.000000e+00,1.727000e+01
max,2.650000e+02,2.650000e+02,1.310510e+03,7.209300e+04,1.336250e+03,9.300000e+01,6.958000e+01,9.613000e+01,8.250000e+00,0.0,1.000000e+02,2.048770e+03

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13392928 entries, 0 to 13392927
Data columns (total 24 columns):
 #   Column                Dtype
---  ------                -----
 0   hvfhs_license_num     object
 1   dispatching_base_num  object
 2   originating_base_num  object
 3   request_datetime      datetime64[ns]
 4   on_scene_datetime     datetime64[ns]
 5   pickup_datetime       datetime64[ns]
 6   dropoff_datetime      datetime64[ns]
 7   PULocationID          int64
 8   DOLocationID          int64
 9   trip_miles            float64
 10  trip_time             int64
 11  base_passenger_fare   float64
 12  tolls                 float64
 13  bcf                   float64
 14  sales_tax             float64
 15  congestion_surcharge  float64
 16  airport_fee           float64
 17  tips                  float64
 18  driver_pay            float64
 19  shared_request_flag   object
 20  shared_match_flag     object
 21  access_a_ride_flag    object
 22  wav_request_flag      object
 23  wav_match_flag        object
dtypes: datetime64[ns](4), float64(9), int64(3), object(8)
memory usage: 2.4+ GB

In [16]:
columns = []
for cols in df.columns:
    columns.append(cols)

In [ ]:
git pull --rebase origin <yourBranchName>
git push origin <yourBranchName>
git push --no-verify